### ISSUE TITLE
paths in email notifications are not updated to the new pagehandlers

### ISSUE THREAD

**Issue by propertunist** [beck24/pagehandler_hijack#1]
not sure if this is a great place to share this.. 
but anyway, i noticed that the email notifications that are sent from elgg that related to, for example, newly created items, that are for entity types that pagehandler hijack has renamed... are being sent with urls that point to the original pagehandler.

e.g. https://www.ureka.org/blog/view/8205/how-facebook-and-youtube-google-are-censoring-and-socially-manipulating-us-and-how-urekaorg-is-different
instead of:
https://www.ureka.org/thoughts/view/8205/how-facebook-and-youtube-google-are-censoring-and-socially-manipulating-us-and-how-urekaorg-is-different

**Comment by beck24** [comment]
This functionality has been added to the 1.9+ version
