### ISSUE TITLE
Issue with Elgg 1.9.8

### ISSUE THREAD

**Issue by gerard-kanters** [beck24/pagehandler_hijack#2]
The plugin still functions in 1.9 but you cannot manage the handeler. The error in the log states

Invalid argument supplied for foreach() in file mod/pagehandler_hijack/views/default/plugins/pagehandler_hijack/settings.php (line 25) 

Maybe related to the use of $CONFIG ?

**Comment by beck24** [comment]
Yeah, it needs to use private API now unfortunately

**Comment by gerard-kanters** [comment]
I really love this plugin and without it I will not upgrade. I probably could do it as well, but my head is in over 100 plugins giving deprecated notices, WSOD and strange behaviour like missing images, member pages gone and the list goes on and on.. 

I know you are extremely busy as well, but hope you can find the time.

**Comment by beck24** [comment]
1.9 compatibility is done

**Comment by gerard-kanters** [comment]
Cool !
